"""SHACL shapes over the ``salg:`` vocabulary — structural validation for an
algebra graph (LLM-authored or hand-authored) *before* attempting
``from_rdf.rdf_to_query``/``rdf_to_update``.

Scope: Phase 1's core graph-pattern operators (``BGP``, ``Filter``,
``LeftJoin``, ``Union``, ``Extend``) plus the ``TriplePattern``/``Variable``
conventions and the ``SELECT`` query wrapper (``Project``/``SelectQuery``),
and — from Phase 2 — ``VALUES`` and subqueries: ``Join``, ``ToMultiSet``,
the ``values``/``Binding`` VALUES-row shapes, and the ``Slice``/``OrderBy``/
``OrderCondition`` subquery-wrapper shapes. Still not covered: property
paths, aggregates/``GROUP BY``, Update, ``MINUS``/``SERVICE``,
``CONSTRUCT``/``ASK``/``DESCRIBE``-specific shapes. Each needs its own
shapes added the same way — see ``salg:GraphPatternShape``'s ``sh:or`` list
in ``SHAPES_TURTLE`` below, which is the one place a new operator's shape
must be registered for it to be accepted inside a nested
``p``/``p1``/``p2`` position.

Full expression-tree validation (``Filter``/``LeftJoin``/``Extend``/
``OrderCondition``'s ``expr``) is now done — all 63 of rdflib's expression
builtins (see ``from_rdf._discover_expr_evalfns``) have their own shape,
grouped into reusable argument-signature families; see
``salg:ExpressionShape`` and ``_EXPR_NODE_FAMILY`` below. One deliberate
exception: ``Builtin_EXISTS``/``Builtin_NOTEXISTS``'s ``.graph`` property
is a *raw, untranslated* SPARQL parse-tree fragment (rdflib evaluates
``EXISTS``/``NOT EXISTS`` lazily, translating it on demand at evaluation
time rather than at parse time) — a genuinely different vocabulary from
the translated-algebra shapes everything else here targets, confirmed by
inspecting real decoded algebra output; validating that separate
vocabulary is out of scope for this pass, so ``.graph`` is checked for
cardinality only, same as the still-open gaps above.

**Known limitation, shared with ``GraphPatternShape``: this file uses
``sh:class`` (a plain type-membership check), never ``sh:node``, inside
any dispatch ``sh:or`` list (``GraphPatternShape``, ``ExpressionShape``)
— never the reverse.** ``sh:node`` triggers full recursive shape
conformance and pushes onto pyshacl's own shape-evaluation stack;
``pyshacl``'s shape-recursion guard (``constraints/
constraint_component.py::recursion_triggers``) tracks *shape identity*
in that stack, not (shape, focus-node) pairs, so it cannot distinguish a
true data cycle from a merely-deep-but-finite tree — and confirmed
empirically to misfire on very shallow, everyday queries (not just
pathologically deep ones) when a dispatch shape's own alternatives loop
back to it via ``sh:node``. ``sh:class`` never touches that stack, so
this is safe regardless of query depth — see ``GraphPatternShape``'s own
comment in ``SHAPES_TURTLE`` for the full account, including how this
was actually discovered (a real, previously-undetected gap: ``Extend``,
``BIND``'s algebra node, was missing from ``GraphPatternShape`` entirely
and nothing caught it, because the old ``sh:node``-based dispatch was
silently giving up before it ever reached that check).

Unlike ``to_rdf.py``/``from_rdf.py``, these shapes are hand-authored, not
generated by introspecting rdflib — rdflib has no static schema of "which
keys does a BGP CompValue have" to introspect (they're just assembled ad
hoc inside ``algebra.py``'s translate functions), so there's no live
source of truth to mirror mechanically the way ``_discover_expr_evalfns``
mirrors the parser grammar.

**Known limitation: shape-graph recursion.** ``GraphPatternShape`` (the
"what's valid inside a nested ``p``/``p1``/``p2`` position" shape) refers
to itself indirectly through ``FilterShape``/``LeftJoinShape``/
``UnionShape`` — genuine recursion, since SPARQL patterns nest to
arbitrary depth. SHACL Core does not require conforming processors to
support recursive shapes at all (see
https://www.w3.org/TR/shacl/#shapes-recursion), and pyshacl's concrete
behavior is: after ~3 revisits of the *same* shape in a row it silently
stops validating that branch and treats it as conformant (a
``ShapeRecursionWarning``, not an error) rather than raising. In practice
this means a query nesting the same operator (e.g. ``OPTIONAL`` inside
``OPTIONAL`` inside ``OPTIONAL``...) more than ~3 levels deep will not have
its deepest levels structurally checked — a false-negative risk, not a
false-positive one (it can miss a malformed deep node, it won't reject a
well-formed one). ``rdf:List`` traversal (``BGP.triples``) is *not*
subject to this, since ``TriplePatternListShape`` below is a single
SPARQL-based constraint rather than a recursively-self-referential
NodeShape, specifically to avoid this. Revisit if deep operator nesting
turns out to matter in practice - e.g. by moving the operator-alternation
check to a SPARQL-based constraint the same way the list shape was.
"""

from __future__ import annotations

import warnings

from rdflib import Graph

from .expr_families import _EXPR_NODE_FAMILY
from .ontology import ontology_graph

try:
    from pyshacl import validate as _pyshacl_validate
    from pyshacl.errors import ShapeRecursionWarning
except ImportError as exc:  # pragma: no cover - exercised only when pyshacl isn't installed
    raise ImportError(
        "starsparql.shapes requires pyshacl - install with "
        "`pip install -e '.[test]'` or `pip install pyshacl`"
    ) from exc

SHAPES_TURTLE = """
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix salg: <https://github.com/hidden-graph/starsparql/ns/algebra#> .

# ---------------------------------------------------------------------
# Shared building blocks
# ---------------------------------------------------------------------

# A SPARQL Variable is encoded as Literal(name, datatype=salg:Variable) —
# see vocab.py's "Variables" section.
salg:VariableShape
    a sh:NodeShape ;
    sh:nodeKind sh:Literal ;
    sh:datatype salg:Variable .

# A triple-pattern subject: a bound IRI/blank node, or a Variable. (Not a
# plain Literal - illegal in RDF subject position, and a real Variable
# would already carry the salg:Variable datatype above.)
#
# The blank-node alternative explicitly excludes a node also typed
# salg:TripleTerm: sh:nodeKind sh:BlankNode alone can't tell an ordinary
# blank-node term apart from a blank node that's structurally the root of a
# salg:TripleTerm (Phase 6) - both are blank nodes at the plain-RDF level.
# This matters because salg:TripleTermShape's own subject property reuses
# this shape specifically to forbid nesting (RDF 1.2 restricts a triple
# term's subject to never be another triple term) - without this exclusion
# a nested TripleTerm would silently conform as "just a blank node". Found
# by a negative SHACL test (test_nested_triple_term_in_subject_position_fails)
# that initially passed when it should have failed.
salg:SubjectOrVariableShape
    a sh:NodeShape ;
    sh:or (
        [ sh:nodeKind sh:IRI ]
        [ sh:nodeKind sh:BlankNode ; sh:not [ a salg:TripleTerm ] ]
        salg:VariableShape
    ) .

# A triple-pattern predicate: a bound IRI, or a Variable. Deliberately
# does NOT include salg:PathShape (see salg:PredicateOrVariableOrPathShape
# below, used by TriplePatternShape instead) - this narrower shape stays
# reserved for TripleTermShape's own predicate, where a property path is
# never legal (RDF 1.2's tripleTerm production restricts its own verb to a
# plain iri - confirmed via grammar12.py's own _TripleTermPredicate, built
# from Var | iri only, no Path alternative spliced in).
salg:PredicateOrVariableShape
    a sh:NodeShape ;
    sh:or ( [ sh:nodeKind sh:IRI ] salg:VariableShape ) .

# An ordinary triple *pattern*'s own predicate additionally allows a
# property path (?s :knows+ ?o) - legal there but never inside a
# TripleTerm (see salg:PredicateOrVariableShape's own comment above for
# why the two need separate shapes despite the near-identical name).
salg:PredicateOrVariableOrPathShape
    a sh:NodeShape ;
    sh:or ( [ sh:nodeKind sh:IRI ] salg:VariableShape salg:PathShape ) .

# A triple-pattern object: any RDF term, or a Variable.
salg:ObjectOrVariableShape
    a sh:NodeShape ;
    sh:or (
        [ sh:nodeKind sh:IRI ]
        [ sh:nodeKind sh:BlankNode ]
        [ sh:nodeKind sh:Literal ]
        salg:VariableShape
    ) .

salg:TriplePatternShape
    a sh:NodeShape ;
    sh:targetClass salg:TriplePattern ;
    sh:property [
        sh:path salg:subject ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:SubjectOrVariableOrTripleTermShape ;
        sh:message "salg:TriplePattern must have exactly one salg:subject, an IRI/blank node/Variable/TripleTerm" ;
    ] ;
    sh:property [
        sh:path salg:predicate ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:PredicateOrVariableOrPathShape ;
        sh:message "salg:TriplePattern must have exactly one salg:predicate, an IRI/Variable/property-path" ;
    ] ;
    sh:property [
        sh:path salg:object ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:ObjectOrVariableOrTripleTermShape ;
        sh:message "salg:TriplePattern must have exactly one salg:object" ;
    ] .

# Phase 6 (SPARQL 1.2): a triple term (salg:TripleTerm) is legal wherever an
# ordinary triple pattern's subject or object is — confirmed empirically
# against the real grammar (grammar12.py) — but NOT wherever its predicate
# is: RDF has always restricted predicate position to IRIs (never a Literal,
# BlankNode, or TripleTerm), a constraint this project's grammar extension
# deliberately preserves (only GraphTerm/VarOrTerm/GraphNode/GraphNodePath
# were extended, not VarOrIri/Verb) - so salg:PredicateOrVariableShape above
# is intentionally left unchanged, not an oversight.
salg:SubjectOrVariableOrTripleTermShape
    a sh:NodeShape ;
    sh:or ( salg:SubjectOrVariableShape salg:TripleTermShape ) .

salg:ObjectOrVariableOrTripleTermShape
    a sh:NodeShape ;
    sh:or ( salg:ObjectOrVariableShape salg:TripleTermShape ) .

# salg:TripleTerm's own subject slot is deliberately NOT
# SubjectOrVariableOrTripleTermShape but plain SubjectOrVariableShape:
# RDF 1.2 restricts a triple term's subject to an IRI/blank node/Variable,
# never another (nested) triple term — nesting is only legal in object
# position. Confirmed both by the grammar (_TripleTermSubject in
# grammar12.py is built from independent Var/iri/BlankNode primitives, not
# the mutable VarOrTerm/GraphTerm objects the nested-triple-term alternative
# is spliced into) and empirically (parsing a nested triple term in subject
# position is rejected).
salg:TripleTermShape
    a sh:NodeShape ;
    sh:targetClass salg:TripleTerm ;
    sh:property [
        sh:path salg:subject ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:SubjectOrVariableShape ;
        sh:message "salg:TripleTerm must have exactly one salg:subject, an IRI/blank node/Variable (nested TripleTerm not permitted here)" ;
    ] ;
    sh:property [
        sh:path salg:predicate ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:PredicateOrVariableShape ;
        sh:message "salg:TripleTerm must have exactly one salg:predicate, an IRI/Variable" ;
    ] ;
    sh:property [
        sh:path salg:object ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:ObjectOrVariableOrTripleTermShape ;
        sh:message "salg:TripleTerm must have exactly one salg:object" ;
    ] .

# A well-formed rdf:List whose members are all salg:TriplePattern.
#
# Deliberately a single SPARQL-based constraint (sh:sparql), not a
# recursively-self-referential NodeShape walking rdf:first/rdf:rest one
# sh:property hop at a time: pyshacl treats each such hop as shape-graph
# recursion (SHACL Core doesn't require recursive-shape support - see
# https://www.w3.org/TR/shacl/#shapes-recursion) and both (a) silently stops
# validating - and reports *conformant* - past ~3 revisits of the same
# shape, and (b) hits pyshacl's hard `max_validation_depth` hard error well
# before that for any BGP with more than a couple of triples, since each
# rdf:List cons cell costs ~4-5 steps of path depth. A single sh:sparql
# constraint checks the whole list in one query instead, at constant path
# depth regardless of list length.
salg:TriplePatternListShape
    a sh:NodeShape ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "expected a well-formed rdf:List of salg:TriplePattern" ;
        sh:select \"\"\"
            PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            PREFIX salg: <https://github.com/hidden-graph/starsparql/ns/algebra#>
            SELECT $this
            WHERE {
                {
                    FILTER ( $this != rdf:nil )
                    FILTER NOT EXISTS { $this rdf:first ?head }
                } UNION {
                    $this rdf:rest*/rdf:first ?item .
                    FILTER NOT EXISTS { ?item a salg:TriplePattern }
                }
            }
        \"\"\" ;
    ] .

# Property paths (?s :knows+ ?o, ?s (:a|:b)/^:c ?o, ...) - already encoded
# by to_rdf._encode_path (confirmed by reading it), never previously
# shaped. salg:PathShape is a dispatch shape (sh:class, rule matches
# GraphPatternShape/ExpressionShape above - see their own comments for why
# sh:class not sh:node/sh:or-of-shapes here).
salg:PathShape
    a sh:NodeShape ;
    sh:class salg:Path ;
    sh:message "expected a recognized property-path operator (see salg:Path in salg-ontology.ttl)" .

# A single path/IRI value - InvPath/MulPath's own salg:arg/salg:path, and
# each member of a SequencePath/AlternativePath/NegatedPath's salg:args
# list.
salg:PathOrIriShape
    a sh:NodeShape ;
    sh:or ( [ sh:nodeKind sh:IRI ] salg:PathShape ) .

# A well-formed rdf:List of path/IRI values (SequencePath/AlternativePath/
# NegatedPath's own salg:args). Same sh:sparql-not-recursive-NodeShape
# pattern as ExpressionListShape below, and deliberately not type-checking
# individual members the same way: a Path-typed item is already
# independently validated by its own targetClass shape wherever it
# appears, and a plain IRI needs no further check.
salg:PathArgsListShape
    a sh:NodeShape ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "expected a well-formed rdf:List of path/IRI values" ;
        sh:select \"\"\"
            PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            SELECT $this
            WHERE {
                {
                    FILTER ( $this != rdf:nil )
                    FILTER NOT EXISTS { $this rdf:first ?head }
                } UNION {
                    $this rdf:rest+ ?tail .
                    FILTER ( ?tail != rdf:nil )
                    FILTER NOT EXISTS { ?tail rdf:first ?tailHead }
                }
            }
        \"\"\" ;
    ] .

salg:InvPathShape
    a sh:NodeShape ;
    sh:targetClass salg:InvPath ;
    sh:property [
        sh:path salg:arg ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:PathOrIriShape ;
        sh:message "salg:InvPath must have exactly one salg:arg, a path or IRI" ;
    ] .

salg:SequencePathShape
    a sh:NodeShape ;
    sh:targetClass salg:SequencePath ;
    sh:property [
        sh:path salg:args ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:PathArgsListShape ;
        sh:message "salg:SequencePath must have exactly one salg:args, a well-formed rdf:List of path/IRI values" ;
    ] .

salg:AlternativePathShape
    a sh:NodeShape ;
    sh:targetClass salg:AlternativePath ;
    sh:property [
        sh:path salg:args ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:PathArgsListShape ;
        sh:message "salg:AlternativePath must have exactly one salg:args, a well-formed rdf:List of path/IRI values" ;
    ] .

salg:MulPathShape
    a sh:NodeShape ;
    sh:targetClass salg:MulPath ;
    sh:property [
        sh:path salg:path ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:PathOrIriShape ;
        sh:message "salg:MulPath must have exactly one salg:path, a path or IRI" ;
    ] ;
    sh:property [
        sh:path salg:mod ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:message "salg:MulPath must have exactly one salg:mod, a bare asterisk/plus/question-mark modifier string" ;
    ] .

salg:NegatedPathShape
    a sh:NodeShape ;
    sh:targetClass salg:NegatedPath ;
    sh:property [
        sh:path salg:args ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:PathArgsListShape ;
        sh:message "salg:NegatedPath must have exactly one salg:args, a well-formed rdf:List of path/IRI values" ;
    ] .

# A well-formed rdf:List whose members are all salg:OrderCondition
# (OrderBy.expr). Same sh:sparql-not-recursive-NodeShape rationale as
# TriplePatternListShape above.
salg:OrderConditionListShape
    a sh:NodeShape ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "expected a well-formed rdf:List of salg:OrderCondition" ;
        sh:select \"\"\"
            PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            PREFIX salg: <https://github.com/hidden-graph/starsparql/ns/algebra#>
            SELECT $this
            WHERE {
                {
                    FILTER ( $this != rdf:nil )
                    FILTER NOT EXISTS { $this rdf:first ?head }
                } UNION {
                    $this rdf:rest*/rdf:first ?item .
                    FILTER NOT EXISTS { ?item a salg:OrderCondition }
                }
            }
        \"\"\" ;
    ] .

# A well-formed rdf:List of "rows" (Values.res), where each row is itself a
# well-formed rdf:List of salg:Binding nodes — see vocab.py's "Binding
# rows" section for the two-level rdf:List shape this mirrors. One level
# deeper than TriplePatternListShape/OrderConditionListShape, same
# sh:sparql-not-recursive-NodeShape rationale.
salg:BindingRowListShape
    a sh:NodeShape ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "expected a well-formed rdf:List of binding rows (each itself a well-formed rdf:List of salg:Binding)" ;
        sh:select \"\"\"
            PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            PREFIX salg: <https://github.com/hidden-graph/starsparql/ns/algebra#>
            SELECT $this
            WHERE {
                {
                    FILTER ( $this != rdf:nil )
                    FILTER NOT EXISTS { $this rdf:first ?head }
                } UNION {
                    $this rdf:rest*/rdf:first ?row .
                    FILTER ( ?row != rdf:nil )
                    FILTER NOT EXISTS { ?row rdf:first ?rowHead }
                } UNION {
                    $this rdf:rest*/rdf:first ?row .
                    ?row rdf:rest*/rdf:first ?binding .
                    FILTER NOT EXISTS { ?binding a salg:Binding }
                }
            }
        \"\"\" ;
    ] .

salg:BindingShape
    a sh:NodeShape ;
    sh:targetClass salg:Binding ;
    sh:property [
        sh:path salg:var ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:VariableShape ;
        sh:message "salg:Binding must have exactly one salg:var, a Variable" ;
    ] ;
    sh:property [
        sh:path salg:val ;
        sh:maxCount 1 ;
        sh:message "salg:Binding may have at most one salg:val (omitted means UNDEF)" ;
    ] .

# ---------------------------------------------------------------------
# Phase 1 core graph-pattern operators (BGP / Filter / LeftJoin / Union)
# ---------------------------------------------------------------------

salg:BGPShape
    a sh:NodeShape ;
    sh:targetClass salg:BGP ;
    sh:property [
        sh:path salg:triples ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:TriplePatternListShape ;
        sh:message "salg:BGP must have exactly one salg:triples, a well-formed rdf:List of salg:TriplePattern" ;
    ] .

# Any value valid in a nested graph-pattern position (Filter.p, LeftJoin.p1/
# p2, Union.p1/p2, Project.p): a member of salg:GraphPattern (see
# salg-ontology.ttl - BGP/Filter/LeftJoin/Union/Join/ToMultiSet/OrderBy/
# Extend are all rdfs:subClassOf salg:GraphPattern). Adding a new operator
# means adding one rdfs:subClassOf triple to the ontology, not touching
# this shape at all.
#
# sh:class, not sh:node to a per-operator shape name: this is a plain
# type-membership check ("is the value's rdf:type - asserted or, with
# validate()'s RDFS reasoning on, entailed via the ontology - a
# salg:GraphPattern"), not a full shape-conformance re-validation. That
# distinction mattered a lot before this shape was simplified to a single
# sh:class check: GraphPatternShape used to be sh:or'd across every
# concrete operator by name (sh:node salg:BGPShape, sh:node
# salg:FilterShape, ...), and pyshacl's shape-recursion guard
# (constraints/constraint_component.py::recursion_triggers) tracks *shape
# identity* in its own evaluation stack, not (shape, focus-node) pairs -
# it can't tell a true data cycle from a merely-deep-but-finite tree, and
# trying every sh:or alternative (most of which looped back to
# GraphPatternShape) tripped that guard on almost any real query, not
# just pathologically deep ones: a plain
# `SELECT ?x WHERE { ?s :p ?y . BIND(STR(?y) AS ?x) }` (4 levels of real
# nesting) produced a "14-22 levels deep" ShapeRecursionWarning and
# pyshacl silently treated the unchecked branch as conformant - which is
# exactly how `Extend` (BIND's algebra node) went unnoticed as missing
# from this list for as long as it did. A single sh:class check against
# the ontology's superclass never touches that evaluation stack at all,
# so there's no recursion-guard exposure left to worry about - and it's
# simpler than the enumerated version ever was, not just safer. Every
# individual operator shape (BGPShape, FilterShape, etc) is completely
# unaffected by any of this - each still has its own sh:targetClass,
# still gets validated fully and independently by pyshacl for every
# matching node in the graph regardless of nesting depth.
salg:GraphPatternShape
    a sh:NodeShape ;
    sh:class salg:GraphPattern ;
    sh:message "expected a recognized graph-pattern operator (see salg:GraphPattern in salg-ontology.ttl)" .

salg:FilterShape
    a sh:NodeShape ;
    sh:targetClass salg:Filter ;
    sh:property [
        sh:path salg:expr ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:ExpressionShape ;
        sh:message "salg:Filter must have exactly one salg:expr" ;
    ] ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:Filter must have exactly one salg:p, a graph pattern" ;
    ] .

# BIND(expr AS ?var) - the one operator this file never had a shape for at
# all (see GraphPatternShape's own docstring above for how that gap
# stayed hidden). salg:p is the *upstream* pattern being extended (join
# order: BIND sees bindings from .p already in scope), not wrapped inside
# it - same "salg:p is whatever comes before this operator" convention as
# every other operator shape here.
salg:ExtendShape
    a sh:NodeShape ;
    sh:targetClass salg:Extend ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:Extend must have exactly one salg:p, a graph pattern" ;
    ] ;
    sh:property [
        sh:path salg:expr ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:ExpressionShape ;
        sh:message "salg:Extend must have exactly one salg:expr" ;
    ] ;
    sh:property [
        sh:path salg:var ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:VariableShape ;
        sh:message "salg:Extend must have exactly one salg:var, a Variable" ;
    ] .

salg:LeftJoinShape
    a sh:NodeShape ;
    sh:targetClass salg:LeftJoin ;
    sh:property [
        sh:path salg:p1 ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:LeftJoin must have exactly one salg:p1, a graph pattern" ;
    ] ;
    sh:property [
        sh:path salg:p2 ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:LeftJoin must have exactly one salg:p2, a graph pattern" ;
    ] ;
    sh:property [
        sh:path salg:expr ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:ExpressionShape ;
        sh:message "salg:LeftJoin must have exactly one salg:expr (TrueFilter if OPTIONAL had no inline FILTER)" ;
    ] .

salg:UnionShape
    a sh:NodeShape ;
    sh:targetClass salg:Union ;
    sh:property [
        sh:path salg:p1 ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:Union must have exactly one salg:p1, a graph pattern" ;
    ] ;
    sh:property [
        sh:path salg:p2 ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:Union must have exactly one salg:p2, a graph pattern" ;
    ] .

salg:MinusShape
    a sh:NodeShape ;
    sh:targetClass salg:Minus ;
    sh:property [
        sh:path salg:p1 ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:Minus must have exactly one salg:p1, a graph pattern" ;
    ] ;
    sh:property [
        sh:path salg:p2 ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:Minus must have exactly one salg:p2, a graph pattern" ;
    ] .

# salg:graph is deliberately cardinality-only, same treatment as
# Builtin_EXISTS/NOTEXISTS's own salg:graph below - confirmed directly
# against live rdflib algebra output that it's a raw, untranslated
# GroupGraphPatternSub/TriplesBlock parse-tree fragment (rdflib evaluates
# SERVICE by re-parsing this on demand at evaluation time, not at
# translate time), a genuinely different, out-of-scope vocabulary from
# everything else this file targets.
salg:ServiceGraphPatternShape
    a sh:NodeShape ;
    sh:targetClass salg:ServiceGraphPattern ;
    sh:property [
        sh:path salg:term ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:message "salg:ServiceGraphPattern must have exactly one salg:term, the endpoint IRI or Variable" ;
    ] ;
    sh:property [
        sh:path salg:graph ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:message "salg:ServiceGraphPattern must have exactly one salg:graph (a raw, untranslated parse-tree fragment - out of scope to shape further, see this property's own comment)" ;
    ] ;
    sh:property [
        sh:path salg:silent ;
        sh:maxCount 1 ;
        sh:message "salg:silent is optional but at most one" ;
    ] .

# ---------------------------------------------------------------------
# Phase 2: VALUES and subqueries (Join / ToMultiSet / values / Binding /
# Slice / OrderBy / OrderCondition)
# ---------------------------------------------------------------------

# Join.p1/p2 both being GraphPatternShape covers e.g. `BGP JOIN ToMultiSet`
# (a BGP combined with an inline VALUES or a subquery).
salg:JoinShape
    a sh:NodeShape ;
    sh:targetClass salg:Join ;
    sh:property [
        sh:path salg:p1 ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:Join must have exactly one salg:p1, a graph pattern" ;
    ] ;
    sh:property [
        sh:path salg:p2 ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:Join must have exactly one salg:p2, a graph pattern" ;
    ] .

# ToMultiSet wraps either an inline VALUES clause (salg:values) or a
# subquery (salg:SubSelectShape: Project, optionally wrapped in Slice/
# OrderBy) — see vocab.py / to_rdf.py, there is no separate marker between
# the two, only the shape of .p distinguishes them.
salg:ToMultiSetShape
    a sh:NodeShape ;
    sh:targetClass salg:ToMultiSet ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node [ sh:or ( salg:valuesShape salg:SubSelectShape ) ] ;
        sh:message "salg:ToMultiSet must have exactly one salg:p, a VALUES clause (salg:values) or a subquery" ;
    ] .

salg:valuesShape
    a sh:NodeShape ;
    sh:targetClass salg:values ;
    sh:property [
        sh:path salg:res ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:BindingRowListShape ;
        sh:message "salg:values must have exactly one salg:res, a well-formed rdf:List of binding rows" ;
    ] .

# ---------------------------------------------------------------------
# GROUP BY / aggregates (Group / AggregateJoin / Aggregate_*) - confirmed
# via translateQuery against real query text: Group{p, expr}, AggregateJoin
# {A, p}. salg:expr is confirmed OPTIONAL on Group - absent entirely
# (Python None, not an empty list) for implicit single-group aggregation
# with no explicit GROUP BY clause at all (e.g. a bare `SELECT (COUNT(?o)
# AS ?c) WHERE {...}`); when present, a well-formed rdf:List of
# expression-position values (reusing ExpressionListShape - GROUP BY ?s
# uses a bare Variable, which already fits).
#
# Known, separate, pre-existing gap found while confirming this (not a
# shapes.py/ontology gap - flagged for a later, different session, out of
# scope here): `GROUP BY (?o+1)` (an *expression*-valued grouping key, as
# opposed to a bare variable) crashes to_rdf.py's own encoder outright
# (AssertionError: Object None must be an rdflib term, inside
# _build_rdf_list) - confirmed via direct reproduction, unrelated to any
# shape. The plain-variable and no-explicit-GROUP BY forms this file's own
# tests use are unaffected.
# ---------------------------------------------------------------------

salg:GroupShape
    a sh:NodeShape ;
    sh:targetClass salg:Group ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:Group must have exactly one salg:p, a graph pattern" ;
    ] ;
    sh:property [
        sh:path salg:expr ;
        sh:maxCount 1 ;
        sh:node salg:ExpressionListShape ;
        sh:message "salg:Group's salg:expr, if present, must be a well-formed rdf:List of grouping-key expressions (absent means implicit single-group aggregation)" ;
    ] .

# A well-formed rdf:List of salg:Aggregate - same sh:sparql pattern as
# TriplePatternListShape etc.
salg:AggregateListShape
    a sh:NodeShape ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "expected a well-formed rdf:List of salg:Aggregate" ;
        sh:select \"\"\"
            PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            PREFIX salg: <https://github.com/hidden-graph/starsparql/ns/algebra#>
            SELECT $this
            WHERE {
                {
                    FILTER ( $this != rdf:nil )
                    FILTER NOT EXISTS { $this rdf:first ?head }
                } UNION {
                    $this rdf:rest*/rdf:first ?item .
                    FILTER NOT EXISTS { ?item a salg:Aggregate }
                }
            }
        \"\"\" ;
    ] .

salg:AggregateJoinShape
    a sh:NodeShape ;
    sh:targetClass salg:AggregateJoin ;
    sh:property [
        sh:path salg:A ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:AggregateListShape ;
        sh:message "salg:AggregateJoin must have exactly one salg:A, a well-formed rdf:List of salg:Aggregate" ;
    ] ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:AggregateJoin must have exactly one salg:p, a graph pattern (its own wrapped salg:Group)" ;
    ] .

# Shared {distinct?, vars, res} body - Count/Sum/Min/Max/Avg. salg:vars
# reuses ExpressionShape rather than a narrower term/Variable-only check:
# confirmed COUNT(*)'s own vars is the bare Python string "*" (salg:PyStr-
# tagged), which already conforms to ExpressionShape's own
# ObjectOrVariableShape branch (any Literal, no datatype restriction) with
# no widening needed.
salg:_AggregateBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:distinct ; sh:maxCount 1 ;
        sh:message "salg:distinct is optional but at most one" ;
    ] ;
    sh:property [
        sh:path salg:vars ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:vars" ;
    ] ;
    sh:property [
        sh:path salg:res ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:VariableShape ;
        sh:message "expected exactly one salg:res, the aggregate's own output Variable" ;
    ] .

# Aggregate_Sample only: no salg:distinct at all (confirmed empirically -
# unlike every other aggregate here, SAMPLE's own CompValue has no
# distinct key).
salg:_SampleAggregateBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:vars ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:vars" ;
    ] ;
    sh:property [
        sh:path salg:res ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:VariableShape ;
        sh:message "expected exactly one salg:res, the aggregate's own output Variable" ;
    ] .

# Aggregate_GroupConcat only: adds the optional salg:separator.
salg:_GroupConcatAggregateBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:distinct ; sh:maxCount 1 ;
        sh:message "salg:distinct is optional but at most one" ;
    ] ;
    sh:property [
        sh:path salg:vars ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:vars" ;
    ] ;
    sh:property [
        sh:path salg:separator ; sh:maxCount 1 ;
        sh:message "salg:separator is optional (absent means the SPARQL-default single-space separator) but at most one" ;
    ] ;
    sh:property [
        sh:path salg:res ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:VariableShape ;
        sh:message "expected exactly one salg:res, the aggregate's own output Variable" ;
    ] .

salg:Aggregate_CountShape a sh:NodeShape ; sh:targetClass salg:Aggregate_Count ; sh:node salg:_AggregateBodyShape .
salg:Aggregate_SumShape a sh:NodeShape ; sh:targetClass salg:Aggregate_Sum ; sh:node salg:_AggregateBodyShape .
salg:Aggregate_MinShape a sh:NodeShape ; sh:targetClass salg:Aggregate_Min ; sh:node salg:_AggregateBodyShape .
salg:Aggregate_MaxShape a sh:NodeShape ; sh:targetClass salg:Aggregate_Max ; sh:node salg:_AggregateBodyShape .
salg:Aggregate_AvgShape a sh:NodeShape ; sh:targetClass salg:Aggregate_Avg ; sh:node salg:_AggregateBodyShape .
salg:Aggregate_SampleShape a sh:NodeShape ; sh:targetClass salg:Aggregate_Sample ; sh:node salg:_SampleAggregateBodyShape .
salg:Aggregate_GroupConcatShape a sh:NodeShape ; sh:targetClass salg:Aggregate_GroupConcat ; sh:node salg:_GroupConcatAggregateBodyShape .

# The top of a SELECT algebra tree, minus the outer SelectQuery wrapper
# (used both by ToMultiSet.p for subquery embedding, and by
# SelectQueryShape.p for the top-level query itself — the two are
# identical in shape, only the outermost query additionally gets
# salg:Query/salg:SelectQuery, see to_rdf.query_to_rdf). Always bottoms out
# at Project, optionally wrapped in any combination of Slice/Distinct/
# Reduced (confirmed empirically via rdflib's algebra output: SELECT
# DISTINCT ... ORDER BY ... LIMIT n produces Slice(Distinct(Project(...))))
# — NOT OrderBy, which wraps the *inner* WHERE pattern, inside Project, not
# outside it (see GraphPatternShape above, not here).
#
# sh:class salg:SubSelect (see salg-ontology.ttl), not sh:or of the four
# shape names: Slice/Distinct/Reduced's own .p all point back at this
# shape (Project is the only non-recursive alternative), the same
# shape-graph-recursion exposure GraphPatternShape had before its own fix
# earlier this session — found while auditing for other instances of that
# pattern, not yet observed to misfire in practice (only reached 3 levels
# deep in the one real query tested: Slice(Distinct(Project(...)))), but
# the mechanism is identical, so fixed the same way rather than left as a
# latent risk.
salg:SubSelectShape
    a sh:NodeShape ;
    sh:class salg:SubSelect ;
    sh:message "expected a subquery pattern (Project, optionally wrapped in Slice/Distinct/Reduced)" .

salg:SliceShape
    a sh:NodeShape ;
    sh:targetClass salg:Slice ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:SubSelectShape ;
        sh:message "salg:Slice must have exactly one salg:p, a subquery pattern" ;
    ] ;
    sh:property [
        sh:path salg:start ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:datatype <http://www.w3.org/2001/XMLSchema#integer> ;
        sh:message "salg:Slice must have exactly one salg:start, an xsd:integer" ;
    ] ;
    sh:property [
        sh:path salg:length ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:datatype <http://www.w3.org/2001/XMLSchema#integer> ;
        sh:message "salg:Slice must have exactly one salg:length, an xsd:integer" ;
    ] .

salg:DistinctShape
    a sh:NodeShape ;
    sh:targetClass salg:Distinct ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:SubSelectShape ;
        sh:message "salg:Distinct must have exactly one salg:p, a subquery pattern" ;
    ] .

salg:ReducedShape
    a sh:NodeShape ;
    sh:targetClass salg:Reduced ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:SubSelectShape ;
        sh:message "salg:Reduced must have exactly one salg:p, a subquery pattern" ;
    ] .

# OrderBy sits *inside* Project, wrapping the WHERE pattern being ordered
# (Project.p = OrderBy(p=<pattern>)) — a graph-pattern-position operator
# like Filter/LeftJoin, not a SubSelectShape wrapper. Registered into
# GraphPatternShape's sh:or above, not SubSelectShape's.
salg:OrderByShape
    a sh:NodeShape ;
    sh:targetClass salg:OrderBy ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:OrderBy must have exactly one salg:p, a graph pattern" ;
    ] ;
    sh:property [
        sh:path salg:expr ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:OrderConditionListShape ;
        sh:message "salg:OrderBy must have exactly one salg:expr, a well-formed rdf:List of salg:OrderCondition" ;
    ] .

salg:OrderConditionShape
    a sh:NodeShape ;
    sh:targetClass salg:OrderCondition ;
    sh:property [
        sh:path salg:expr ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:ExpressionShape ;
        sh:message "salg:OrderCondition must have exactly one salg:expr" ;
    ] ;
    sh:property [
        sh:path salg:order ;
        sh:maxCount 1 ;
        sh:message "salg:OrderCondition may have at most one salg:order (omitted means ASC)" ;
    ] .

# ---------------------------------------------------------------------
# SELECT query wrapper (Project / SelectQuery) - needed to validate a
# complete, executable Phase-1-shaped query, not just a bare graph pattern.
# ---------------------------------------------------------------------

salg:ProjectShape
    a sh:NodeShape ;
    sh:targetClass salg:Project ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:Project must have exactly one salg:p, a graph pattern" ;
    ] ;
    sh:property [
        sh:path salg:PV ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:message "salg:Project must have exactly one salg:PV (the projected-variables list)" ;
    ] .

salg:SelectQueryShape
    a sh:NodeShape ;
    sh:targetClass salg:SelectQuery ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:SubSelectShape ;
        sh:message "salg:SelectQuery must have exactly one salg:p, a subquery pattern (Project, optionally wrapped in Slice/Distinct/Reduced)" ;
    ] ;
    sh:property [
        sh:path salg:PV ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:message "salg:SelectQuery must have exactly one salg:PV (the projected-variables list)" ;
    ] ;
    sh:property [
        sh:path salg:datasetClause ;
        sh:maxCount 1 ;
        sh:message "salg:SelectQuery may have at most one salg:datasetClause" ;
    ] .

# ---------------------------------------------------------------------
# CONSTRUCT / ASK / DESCRIBE query wrappers - confirmed via translateQuery
# against real query text (not guessed): ConstructQuery{p, template,
# datasetClause}, AskQuery{p, datasetClause, PV}, DescribeQuery{p,
# datasetClause, PV}.
# ---------------------------------------------------------------------

salg:ConstructQueryShape
    a sh:NodeShape ;
    sh:targetClass salg:ConstructQuery ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:SubSelectShape ;
        sh:message "salg:ConstructQuery must have exactly one salg:p, a subquery pattern" ;
    ] ;
    sh:property [
        sh:path salg:template ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:TriplePatternListShape ;
        sh:message "salg:ConstructQuery must have exactly one salg:template, a well-formed rdf:List of salg:TriplePattern" ;
    ] ;
    sh:property [
        sh:path salg:datasetClause ;
        sh:maxCount 1 ;
        sh:message "salg:ConstructQuery may have at most one salg:datasetClause" ;
    ] .

salg:AskQueryShape
    a sh:NodeShape ;
    sh:targetClass salg:AskQuery ;
    sh:property [
        sh:path salg:p ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:SubSelectShape ;
        sh:message "salg:AskQuery must have exactly one salg:p, a subquery pattern" ;
    ] ;
    sh:property [
        sh:path salg:PV ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:message "salg:AskQuery must have exactly one salg:PV (always empty for ASK, but the property itself is always present)" ;
    ] ;
    sh:property [
        sh:path salg:datasetClause ;
        sh:maxCount 1 ;
        sh:message "salg:AskQuery may have at most one salg:datasetClause" ;
    ] .

# salg:p is optional here, unlike every other query form: confirmed via
# translateQuery that a bare `DESCRIBE :alice` (no WHERE clause at all)
# produces DescribeQuery{p: None, ...} - p genuinely absent, not an empty
# pattern. salg:PV is also confirmed to mix plain IRIs with Variable-typed
# Literals for this form (DESCRIBE's own described-resource list, not
# necessarily all bound variables) - unproblematic since PV is checked for
# cardinality only here, same as ProjectShape/SelectQueryShape/
# AskQueryShape's own existing PV treatment (no per-member type check).
salg:DescribeQueryShape
    a sh:NodeShape ;
    sh:targetClass salg:DescribeQuery ;
    sh:property [
        sh:path salg:p ;
        sh:maxCount 1 ;
        sh:node salg:SubSelectShape ;
        sh:message "salg:DescribeQuery's salg:p, if present, must be a subquery pattern (absent for a bare DESCRIBE with no WHERE clause)" ;
    ] ;
    sh:property [
        sh:path salg:PV ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:message "salg:DescribeQuery must have exactly one salg:PV (the described variables/IRIs)" ;
    ] ;
    sh:property [
        sh:path salg:datasetClause ;
        sh:maxCount 1 ;
        sh:message "salg:DescribeQuery may have at most one salg:datasetClause" ;
    ] .

# ---------------------------------------------------------------------
# SPARQL Update - all ten operation forms, confirmed via translateUpdate
# against real update text (not guessed): InsertData/DeleteData/
# DeleteWhere{triples, quads}; Modify{delete, insert, where}; DeleteClause/
# InsertClause{triples, quads} (same shape as InsertData etc, but template
# position not pattern position - see CLAUDE.md); Load{iri};
# Clear/Drop/Create{graphiri}; Add/Move/Copy{graph}.
# ---------------------------------------------------------------------

# A graph reference: a real graph term, or a bare DEFAULT/NAMED/ALL keyword
# (salg:PyStr-tagged, see vocab.py's "Bare Python strings" section) -
# Clear/Drop/Create's own salg:graphiri, and each element of Add/Move/
# Copy's salg:graph list.
salg:GraphRefShape
    a sh:NodeShape ;
    sh:or (
        [ sh:nodeKind sh:IRI ]
        [ sh:nodeKind sh:BlankNode ]
        [ sh:nodeKind sh:Literal ; sh:datatype salg:PyStr ]
    ) .

# Add/Move/Copy's own salg:graph - confirmed via translateUpdate a plain
# 2-element Python list [source, dest], not a general-length list like
# every other rdf:List shape in this file - so this checks length exactly
# 2, not just well-formedness, in addition to each item being a
# salg:GraphRefShape. Same sh:sparql-not-recursive-NodeShape approach as
# TriplePatternListShape etc.
salg:GraphRefListShape
    a sh:NodeShape ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "expected a well-formed 2-element rdf:List [source, dest] of graph references (IRI/BlankNode/PyStr DEFAULT keyword)" ;
        sh:select \"\"\"
            PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            PREFIX salg: <https://github.com/hidden-graph/starsparql/ns/algebra#>
            SELECT $this
            WHERE {
                {
                    FILTER NOT EXISTS { $this rdf:first ?first }
                } UNION {
                    FILTER NOT EXISTS { $this rdf:rest/rdf:first ?second }
                } UNION {
                    $this rdf:rest/rdf:rest ?tail .
                    FILTER ( ?tail != rdf:nil )
                } UNION {
                    $this rdf:rest*/rdf:first ?item .
                    FILTER ( !isIRI(?item) && !isBlank(?item) && !(isLiteral(?item) && datatype(?item) = salg:PyStr) )
                }
            }
        \"\"\" ;
    ] .

# One graph-qualified group of triples inside an Update operation's own
# salg:quads list (see vocab.py's "Update quads-by-graph maps" section) -
# salg:QuadsForGraph itself was already written by to_rdf._encode_quads_map
# but had no ontology class declaration at all until this pass.
salg:QuadsForGraphShape
    a sh:NodeShape ;
    sh:targetClass salg:QuadsForGraph ;
    sh:property [
        sh:path salg:graph ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:message "salg:QuadsForGraph must have exactly one salg:graph, the graph term this group of triples is qualified by" ;
    ] ;
    sh:property [
        sh:path salg:triples ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:TriplePatternListShape ;
        sh:message "salg:QuadsForGraph must have exactly one salg:triples, a well-formed rdf:List of salg:TriplePattern" ;
    ] .

# A well-formed rdf:List of salg:QuadsForGraph - same sh:sparql pattern as
# TriplePatternListShape/OrderConditionListShape, just checking a different
# member type.
salg:QuadsForGraphListShape
    a sh:NodeShape ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "expected a well-formed rdf:List of salg:QuadsForGraph" ;
        sh:select \"\"\"
            PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            PREFIX salg: <https://github.com/hidden-graph/starsparql/ns/algebra#>
            SELECT $this
            WHERE {
                {
                    FILTER ( $this != rdf:nil )
                    FILTER NOT EXISTS { $this rdf:first ?head }
                } UNION {
                    $this rdf:rest*/rdf:first ?item .
                    FILTER NOT EXISTS { ?item a salg:QuadsForGraph }
                }
            }
        \"\"\" ;
    ] .

# Shared {triples, quads} body - InsertData/DeleteData/DeleteWhere's own
# ordinary-pattern-position shape, and (same body, different position
# semantics - see CLAUDE.md) DeleteClause/InsertClause's own
# template-position shape. Structurally identical either way, so one
# reusable body shape, same "generate/share a family body" spirit as the
# expression builtins' own _*ExprBodyShape shapes, just not generated
# (only 5 members).
salg:_FlatTriplesUpdateBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:triples ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:TriplePatternListShape ;
        sh:message "expected exactly one salg:triples, a well-formed rdf:List of salg:TriplePattern" ;
    ] ;
    sh:property [
        sh:path salg:quads ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:QuadsForGraphListShape ;
        sh:message "expected exactly one salg:quads, a well-formed rdf:List of salg:QuadsForGraph" ;
    ] .

salg:InsertDataShape a sh:NodeShape ; sh:targetClass salg:InsertData ; sh:node salg:_FlatTriplesUpdateBodyShape .
salg:DeleteDataShape a sh:NodeShape ; sh:targetClass salg:DeleteData ; sh:node salg:_FlatTriplesUpdateBodyShape .
salg:DeleteWhereShape a sh:NodeShape ; sh:targetClass salg:DeleteWhere ; sh:node salg:_FlatTriplesUpdateBodyShape .
salg:DeleteClauseShape a sh:NodeShape ; sh:targetClass salg:DeleteClause ; sh:node salg:_FlatTriplesUpdateBodyShape .
salg:InsertClauseShape a sh:NodeShape ; sh:targetClass salg:InsertClause ; sh:node salg:_FlatTriplesUpdateBodyShape .

# Modify's own salg:delete/salg:insert are each optional (sh:node still
# checks conformance for whichever is present - vacuously satisfied when
# absent, same as every other optional sh:node property in this file) but
# not *both* absent at once - SPARQL's own grammar requires at least one
# clause. The sh:sparql constraint below is the one place in this shape
# that needs a real query rather than sh:property cardinality, since
# "at least one of two independent properties" isn't expressible as a
# per-property minCount.
salg:ModifyShape
    a sh:NodeShape ;
    sh:targetClass salg:Modify ;
    sh:property [
        sh:path salg:delete ;
        sh:maxCount 1 ;
        sh:node salg:DeleteClauseShape ;
        sh:message "salg:Modify's salg:delete, if present, must be a salg:DeleteClause" ;
    ] ;
    sh:property [
        sh:path salg:insert ;
        sh:maxCount 1 ;
        sh:node salg:InsertClauseShape ;
        sh:message "salg:Modify's salg:insert, if present, must be a salg:InsertClause" ;
    ] ;
    sh:property [
        sh:path salg:where ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphPatternShape ;
        sh:message "salg:Modify must have exactly one salg:where, a graph pattern" ;
    ] ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "salg:Modify must have at least one of salg:delete/salg:insert (SPARQL forbids a Modify with neither)" ;
        sh:select \"\"\"
            PREFIX salg: <https://github.com/hidden-graph/starsparql/ns/algebra#>
            SELECT $this
            WHERE {
                FILTER NOT EXISTS { $this salg:delete ?d }
                FILTER NOT EXISTS { $this salg:insert ?i }
            }
        \"\"\" ;
    ] .

salg:LoadShape
    a sh:NodeShape ;
    sh:targetClass salg:Load ;
    sh:property [
        sh:path salg:iri ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:nodeKind sh:IRI ;
        sh:message "salg:Load must have exactly one salg:iri, an IRI" ;
    ] .

# Shared {graphiri} body - Clear/Drop/Create.
salg:_GraphRefUpdateBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:graphiri ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphRefShape ;
        sh:message "expected exactly one salg:graphiri, a graph term or DEFAULT/NAMED/ALL keyword" ;
    ] .

salg:ClearShape a sh:NodeShape ; sh:targetClass salg:Clear ; sh:node salg:_GraphRefUpdateBodyShape .
salg:DropShape a sh:NodeShape ; sh:targetClass salg:Drop ; sh:node salg:_GraphRefUpdateBodyShape .
salg:CreateShape a sh:NodeShape ; sh:targetClass salg:Create ; sh:node salg:_GraphRefUpdateBodyShape .

# Shared {graph} body - Add/Move/Copy.
salg:_GraphRefListUpdateBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:graph ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:GraphRefListShape ;
        sh:message "expected exactly one salg:graph, a 2-element rdf:List [source, dest] of graph references" ;
    ] .

salg:AddShape a sh:NodeShape ; sh:targetClass salg:Add ; sh:node salg:_GraphRefListUpdateBodyShape .
salg:MoveShape a sh:NodeShape ; sh:targetClass salg:Move ; sh:node salg:_GraphRefListUpdateBodyShape .
salg:CopyShape a sh:NodeShape ; sh:targetClass salg:Copy ; sh:node salg:_GraphRefListUpdateBodyShape .

# A well-formed rdf:List of salg:UpdateOperation - same sh:sparql pattern
# as TriplePatternListShape/QuadsForGraphListShape, checking that member
# type instead.
salg:UpdateOperationListShape
    a sh:NodeShape ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "expected a well-formed rdf:List of salg:UpdateOperation" ;
        sh:select \"\"\"
            PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            PREFIX salg: <https://github.com/hidden-graph/starsparql/ns/algebra#>
            SELECT $this
            WHERE {
                {
                    FILTER ( $this != rdf:nil )
                    FILTER NOT EXISTS { $this rdf:first ?head }
                } UNION {
                    $this rdf:rest*/rdf:first ?item .
                    FILTER NOT EXISTS { ?item a salg:UpdateOperation }
                }
            }
        \"\"\" ;
    ] .

# The root of a whole encoded Update request (see to_rdf.update_to_rdf) -
# salg:operations the ordered list of operations. No Prologue-property
# validation here (salg:base/salg:prologuePrefix), matching this file's own
# existing convention of not validating Prologue on SelectQueryShape either.
salg:UpdateShape
    a sh:NodeShape ;
    sh:targetClass salg:Update ;
    sh:property [
        sh:path salg:operations ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:UpdateOperationListShape ;
        sh:message "salg:Update must have exactly one salg:operations, a well-formed rdf:List of salg:UpdateOperation" ;
    ] .

# ---------------------------------------------------------------------
# QueryCollection (see to_rdf.queries_to_collection) - a container node
# grouping independent salg:Query roots, salg:queries an rdf:List of them.
# ---------------------------------------------------------------------

# A well-formed rdf:List of salg:Query - same sh:sparql pattern as
# TriplePatternListShape/UpdateOperationListShape etc.
salg:QueryListShape
    a sh:NodeShape ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "expected a well-formed rdf:List of salg:Query" ;
        sh:select \"\"\"
            PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            PREFIX salg: <https://github.com/hidden-graph/starsparql/ns/algebra#>
            SELECT $this
            WHERE {
                {
                    FILTER ( $this != rdf:nil )
                    FILTER NOT EXISTS { $this rdf:first ?head }
                } UNION {
                    $this rdf:rest*/rdf:first ?item .
                    FILTER NOT EXISTS { ?item a salg:Query }
                }
            }
        \"\"\" ;
    ] .

salg:QueryCollectionShape
    a sh:NodeShape ;
    sh:targetClass salg:QueryCollection ;
    sh:property [
        sh:path salg:queries ;
        sh:minCount 1 ; sh:maxCount 1 ;
        sh:node salg:QueryListShape ;
        sh:message "salg:QueryCollection must have exactly one salg:queries, a well-formed rdf:List of salg:Query" ;
    ] .

# ---------------------------------------------------------------------
# Expression trees (Filter/LeftJoin/Extend/OrderCondition.expr) - rdflib
# has 63 expression builtins (see from_rdf._discover_expr_evalfns); each
# gets its own shape, grouped into families by real argument signature -
# confirmed directly against live rdflib algebra output for every one of
# the 63 (not assumed - arity/key-names vary in ways not guessable from a
# builtin's name alone, e.g. Builtin_REPLACE uses arg/pattern/replacement/
# flags, not arg1/arg2/arg3/arg4, and Builtin_BNODE takes an *optional*
# single arg unlike every other 0-or-1-arg builtin).
#
# Each of the 63 real node names gets a short, generated declaration (see
# _EXPR_NODE_FAMILY/_generate_expression_shapes_turtle below) pointing at
# ONE of the reusable "family body" shapes here via sh:node - avoiding 63
# near-duplicated property blocks. A family body shape has no
# sh:targetClass/sh:class of its own - it's pure reusable constraint,
# never a validation entry point by itself, only ever referenced.
# ---------------------------------------------------------------------

# Any value valid in an expression position (Filter.expr, Extend.expr,
# OrderCondition.expr, any expression node's own operand): a bare bound
# term/Variable (salg:ObjectOrVariableShape - the same "just a value"
# shape already used for TriplePattern.object), or a member of
# salg:Expression (see salg-ontology.ttl - all 63 expression builtins are
# rdfs:subClassOf one of its family classes, which are themselves
# rdfs:subClassOf salg:Expression). Same sh:class-not-sh:node rationale as
# GraphPatternShape above - expression trees nest arbitrarily
# (STR(STR(STR(?x))) is legal SPARQL), so this shape is exactly as
# recursive as GraphPatternShape was and needs the same fix; previously
# this enumerated all 63 classes by name (generated from
# expr_families._EXPR_NODE_FAMILY), now RDFS reasoning (see validate())
# does that enumeration for us.
salg:ExpressionShape
    a sh:NodeShape ;
    sh:or ( salg:ObjectOrVariableShape [ sh:class salg:Expression ] ) ;
    sh:message "expected a legal expression value (a term/Variable, or a recognized expression builtin)" .

# A well-formed rdf:List of expression values (Builtin_CONCAT/COALESCE's
# variadic .arg, Function's .expr call-argument list, and the .other of
# RelationalExpression/ConditionalAndExpression/ConditionalOrExpression/
# AdditiveExpression/MultiplicativeExpression when it's a list). Same
# sh:sparql-not-recursive-NodeShape rationale as TriplePatternListShape/
# OrderConditionListShape/BindingRowListShape - but unlike those, list
# items here are deliberately NOT filtered by type: they're heterogeneous
# by design (a bare term or any of the 63 expression classes), and any
# *typed* item is already independently, globally validated by its own
# sh:targetClass shape regardless of where it's referenced from -
# re-checking that here would be redundant, not additive. Second UNION
# branch checks every cons cell along the chain (not just $this itself)
# has a well-formed rdf:first, catching a malformed cell mid-list.
salg:ExpressionListShape
    a sh:NodeShape ;
    sh:sparql [
        a sh:SPARQLConstraint ;
        sh:message "expected a well-formed rdf:List of expression values" ;
        sh:select \"\"\"
            PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
            SELECT $this
            WHERE {
                {
                    FILTER ( $this != rdf:nil )
                    FILTER NOT EXISTS { $this rdf:first ?head }
                } UNION {
                    $this rdf:rest+ ?tail .
                    FILTER ( ?tail != rdf:nil )
                    FILTER NOT EXISTS { ?tail rdf:first ?tailHead }
                }
            }
        \"\"\" ;
    ] .

salg:_ZeroArgExprBodyShape
    a sh:NodeShape .

salg:_OneArgExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:arg ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:arg" ;
    ] .

# Builtin_BNODE only: BNODE() (fresh blank node, no arg) and BNODE(?x)
# (deterministic per binding, one arg) are both legal - confirmed
# directly against live rdflib algebra output, unlike every other
# one-arg builtin where the argument is mandatory.
salg:_OptionalOneArgExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:arg ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "salg:arg is optional (absent means BNODE()'s no-argument form) but at most one" ;
    ] .

salg:_UnaryExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:expr ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:expr" ;
    ] .

salg:_TwoArgExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:arg1 ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:arg1" ;
    ] ;
    sh:property [
        sh:path salg:arg2 ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:arg2" ;
    ] .

salg:_ThreeArgExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:arg1 ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:arg1" ;
    ] ;
    sh:property [
        sh:path salg:arg2 ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:arg2" ;
    ] ;
    sh:property [
        sh:path salg:arg3 ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:arg3" ;
    ] .

# Builtin_CONCAT/COALESCE only: .arg is a *list* here, unlike the
# single-value .arg of the one-arg family above.
salg:_VariadicArgExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:arg ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionListShape ;
        sh:message "expected exactly one salg:arg, a well-formed rdf:List of expression values" ;
    ] .

salg:_RegexExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:text ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:text" ;
    ] ;
    sh:property [
        sh:path salg:pattern ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:pattern" ;
    ] ;
    sh:property [
        sh:path salg:flags ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "salg:flags is optional but at most one" ;
    ] .

salg:_ReplaceExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:arg ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:arg" ;
    ] ;
    sh:property [
        sh:path salg:pattern ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:pattern" ;
    ] ;
    sh:property [
        sh:path salg:replacement ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:replacement" ;
    ] ;
    sh:property [
        sh:path salg:flags ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "salg:flags is optional but at most one" ;
    ] .

salg:_SubstrExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:arg ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:arg" ;
    ] ;
    sh:property [
        sh:path salg:start ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:start" ;
    ] ;
    sh:property [
        sh:path salg:length ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "salg:length is optional but at most one" ;
    ] .

# EXISTS{...}/NOT EXISTS{...}: .graph is deliberately NOT sh:node
# salg:GraphPatternShape. Confirmed directly against live rdflib algebra
# output that .graph is a *raw, untranslated* parse-tree fragment
# (GroupGraphPatternSub/TriplesBlock/part - rdflib's own pre-
# translateGroupGraphPattern shape), not a translated operator like
# every other graph-pattern-position property in this vocabulary -
# rdflib evaluates EXISTS/NOT EXISTS lazily and translates this fragment
# on demand at evaluation time, not at parse time. Validating *that*
# vocabulary (a distinct one from the translated-algebra vocabulary
# every other shape here targets) is out of scope for this pass -
# cardinality-only here, same honest-scoping convention already used for
# the other explicitly-deferred gaps (property paths, aggregates,
# Update, MINUS/SERVICE - see this module's own docstring).
salg:_ExistsExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:graph ; sh:minCount 1 ; sh:maxCount 1 ;
        sh:message "expected exactly one salg:graph" ;
    ] .

salg:_FunctionExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:iri ; sh:minCount 1 ; sh:maxCount 1 ; sh:nodeKind sh:IRI ;
        sh:message "salg:Function must have exactly one salg:iri, an IRI" ;
    ] ;
    sh:property [
        sh:path salg:distinct ; sh:maxCount 1 ;
        sh:message "salg:Function may have at most one salg:distinct" ;
    ] ;
    sh:property [
        sh:path salg:expr ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionListShape ;
        sh:message "salg:Function must have exactly one salg:expr, a well-formed rdf:List of call arguments" ;
    ] .

# .other is a single expression normally (?x = ?y), but a well-formed
# rdf:List for IN/NOT IN (?x IN (?y, ?z)) - confirmed directly against
# live rdflib algebra output for both forms.
salg:_RelationalExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:expr ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:expr" ;
    ] ;
    sh:property [
        sh:path salg:op ; sh:minCount 1 ; sh:maxCount 1 ;
        sh:message "expected exactly one salg:op" ;
    ] ;
    sh:property [
        sh:path salg:other ; sh:minCount 1 ; sh:maxCount 1 ;
        sh:node [ sh:or ( salg:ExpressionShape salg:ExpressionListShape ) ] ;
        sh:message "expected exactly one salg:other, an expression or (for IN/NOT IN) a well-formed rdf:List of expressions" ;
    ] .

# .other is absent for a single-condition degenerate case - confirmed
# directly against rdflib's own ConditionalAndExpression/
# ConditionalOrExpression evalfn source ("if other is None: return
# expr") - a well-formed rdf:List of further conditions when present.
salg:_ConditionalExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:expr ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:expr" ;
    ] ;
    sh:property [
        sh:path salg:other ; sh:maxCount 1 ; sh:node salg:ExpressionListShape ;
        sh:message "salg:other is optional (absent means a single-condition expression) but a well-formed rdf:List of expressions when present" ;
    ] .

# .other is always a list here (?x + ?y - ?z always has other=[y,z]) -
# confirmed directly against live rdflib algebra output; unlike
# ConditionalAndExpression/RelationalExpression, never a bare single
# value or absent.
salg:_ArithmeticExprBodyShape
    a sh:NodeShape ;
    sh:property [
        sh:path salg:expr ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionShape ;
        sh:message "expected exactly one salg:expr" ;
    ] ;
    sh:property [
        sh:path salg:op ; sh:minCount 1 ; sh:maxCount 1 ;
        sh:message "expected exactly one salg:op, a well-formed rdf:List of operator strings" ;
    ] ;
    sh:property [
        sh:path salg:other ; sh:minCount 1 ; sh:maxCount 1 ; sh:node salg:ExpressionListShape ;
        sh:message "expected exactly one salg:other, a well-formed rdf:List of expressions" ;
    ] .
"""


def _generate_expression_shapes_turtle() -> str:
    """The 63 short per-expression-node-name declarations, each pointing
    at its family's reusable body shape via ``sh:node`` - generated from
    ``_EXPR_NODE_FAMILY`` rather than hand-written. See that table's own
    docstring for why.
    """
    declarations = [
        f"salg:{name}Shape a sh:NodeShape ; sh:targetClass salg:{name} ; "
        f"sh:node salg:_{family}ExprBodyShape ."
        for name, family in _EXPR_NODE_FAMILY.items()
    ]
    return "\n".join(declarations) + "\n"


def shapes_graph() -> Graph:
    """A fresh ``rdflib.Graph`` of the shapes above (SHACL graphs are
    mutated by pyshacl during validation, so callers get their own copy
    rather than a shared module-level instance)."""
    turtle = SHAPES_TURTLE + "\n" + _generate_expression_shapes_turtle()
    g = Graph()
    g.parse(data=turtle, format="turtle")
    return g


def validate(data_graph: Graph) -> tuple[bool, Graph, str]:
    """Validate ``data_graph`` (e.g. from ``to_rdf.query_to_rdf``, or an
    LLM-authored ``salg:`` graph not yet decoded) against the shapes above.

    Runs with RDFS reasoning enabled (``ont_graph=ontology_graph()``,
    ``inference="rdfs"``) - this is what lets ``GraphPatternShape``/
    ``ExpressionShape``/``SubSelectShape`` be a single ``sh:class`` check
    against an abstract superclass (``salg:GraphPattern``/``salg:Expression``/
    ``salg:SubSelect``) instead of enumerating every concrete
    operator/builtin by name: with reasoning on, a node asserted as e.g.
    ``salg:Builtin_STR`` is *also* entailed to be ``rdf:type``
    ``salg:OneArgExpression`` and ``salg:Expression`` (the ontology's own
    ``rdfs:subClassOf`` chain), so ``sh:class salg:Expression`` alone
    matches it - confirmed empirically, not assumed. Every individual
    operator/builtin shape (``BGPShape``, ``Builtin_STRShape``, ...) is
    unaffected either way - RDFS subclass reasoning only ever *adds*
    broader inferred types to an already-narrowly-typed node, never
    invents narrower ones, so ``sh:targetClass salg:Builtin_STR`` still
    fires only for nodes actually asserted as that type.

    Returns ``(conforms, results_graph, results_text)`` — the same shape
    ``pyshacl.validate`` itself returns, so a caller that wants the raw
    SHACL validation report can use it directly.
    """
    # No shape in this file's dispatch shapes (GraphPatternShape/
    # ExpressionShape/SubSelectShape) references another shape by name
    # anymore (sh:class, not sh:node/sh:or-of-shapes - see each one's own
    # comment in SHAPES_TURTLE), so pyshacl's shape-recursion guard
    # shouldn't have anything left to trip on. Kept as a defensive
    # suppression, not because it's expected to fire.
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=ShapeRecursionWarning)
        conforms, results_graph, results_text = _pyshacl_validate(
            data_graph,
            shacl_graph=shapes_graph(),
            ont_graph=ontology_graph(),
            inference="rdfs",
            advanced=True,
            max_validation_depth=100,
        )
    return conforms, results_graph, results_text
