"""SHACL shapes over the ``salg:`` vocabulary — structural validation for an
algebra graph (LLM-authored or hand-authored) *before* attempting
``from_rdf.rdf_to_query``/``rdf_to_update``.

Scope: full coverage as of the last update to this docstring (2026-08) —
core graph-pattern operators (``BGP``/``Filter``/``LeftJoin``/``Union``/
``Extend``/``Minus``/``ServiceGraphPattern``/``Join``/``ToMultiSet``), the
``TriplePattern``/``TripleTerm``/``Variable`` conventions, all five property
path types, ``VALUES``, aggregates/``GROUP BY`` (all 7 real
``Aggregate_*`` forms), ``Slice``/``Distinct``/``Reduced``/``OrderBy``,
every query form (``SELECT``/``CONSTRUCT``/``ASK``/``DESCRIBE``), full
SPARQL Update (all ten operations), and ``salg:QueryCollection``. Any new
operator needs its own shape added the same way — see
``salg:GraphPatternShape``'s ``sh:or`` list in ``sparql_shapes.ttl`` (loaded
below as ``SHAPES_TURTLE``), which is the one place a new operator's shape must be registered for it to
be accepted inside a nested ``p``/``p1``/``p2`` position. (This scope note
previously described only Phase 1 + VALUES/subqueries and had drifted well
out of date with the file's actual content by the time this was corrected
— if this note and the shape inventory below ever disagree again, trust
the code: grep for ``^salg:[A-Za-z_]*Shape$`` to get the real, current
list.)

Full expression-tree validation (``Filter``/``LeftJoin``/``Extend``/
``OrderCondition``'s ``expr``) is now done — all 63 of rdflib's expression
builtins (see ``from_rdf._discover_expr_evalfns``) have their own shape,
grouped into reusable argument-signature families; see
``salg:ExpressionShape`` and ``_EXPR_NODE_FAMILY`` below. One deliberate
exception: ``Builtin_EXISTS``/``Builtin_NOTEXISTS``'s ``.graph`` property
is a *raw, untranslated* SPARQL parse-tree fragment (rdflib evaluates
``EXISTS``/``NOT EXISTS`` lazily, translating it on demand at evaluation
time rather than at parse time) — a genuinely different vocabulary from
the translated-algebra shapes everything else here targets, confirmed by
inspecting real decoded algebra output; validating that separate
vocabulary is out of scope for this pass, so ``.graph`` is checked for
cardinality only, same as the still-open gaps above.

**Known limitation, shared with ``GraphPatternShape``: this file uses
``sh:class`` (a plain type-membership check), never ``sh:node``, inside
any dispatch ``sh:or`` list (``GraphPatternShape``, ``ExpressionShape``)
— never the reverse.** ``sh:node`` triggers full recursive shape
conformance and pushes onto pyshacl's own shape-evaluation stack;
``pyshacl``'s shape-recursion guard (``constraints/
constraint_component.py::recursion_triggers``) tracks *shape identity*
in that stack, not (shape, focus-node) pairs, so it cannot distinguish a
true data cycle from a merely-deep-but-finite tree — and confirmed
empirically to misfire on very shallow, everyday queries (not just
pathologically deep ones) when a dispatch shape's own alternatives loop
back to it via ``sh:node``. ``sh:class`` never touches that stack, so
this is safe regardless of query depth — see ``GraphPatternShape``'s own
comment in ``sparql_shapes.ttl`` for the full account, including how this
was actually discovered (a real, previously-undetected gap: ``Extend``,
``BIND``'s algebra node, was missing from ``GraphPatternShape`` entirely
and nothing caught it, because the old ``sh:node``-based dispatch was
silently giving up before it ever reached that check).

Unlike ``to_rdf.py``/``from_rdf.py``, these shapes are hand-authored, not
generated by introspecting rdflib — rdflib has no static schema of "which
keys does a BGP CompValue have" to introspect (they're just assembled ad
hoc inside ``algebra.py``'s translate functions), so there's no live
source of truth to mirror mechanically the way ``_discover_expr_evalfns``
mirrors the parser grammar.

**Known limitation: shape-graph recursion.** ``GraphPatternShape`` (the
"what's valid inside a nested ``p``/``p1``/``p2`` position" shape) refers
to itself indirectly through ``FilterShape``/``LeftJoinShape``/
``UnionShape`` — genuine recursion, since SPARQL patterns nest to
arbitrary depth. SHACL Core does not require conforming processors to
support recursive shapes at all (see
https://www.w3.org/TR/shacl/#shapes-recursion), and pyshacl's concrete
behavior is: after ~3 revisits of the *same* shape in a row it silently
stops validating that branch and treats it as conformant (a
``ShapeRecursionWarning``, not an error) rather than raising. In practice
this means a query nesting the same operator (e.g. ``OPTIONAL`` inside
``OPTIONAL`` inside ``OPTIONAL``...) more than ~3 levels deep will not have
its deepest levels structurally checked — a false-negative risk, not a
false-positive one (it can miss a malformed deep node, it won't reject a
well-formed one). ``rdf:List`` traversal (``BGP.triples``) is *not*
subject to this, since ``TriplePatternListShape`` below is a single
SPARQL-based constraint rather than a recursively-self-referential
NodeShape, specifically to avoid this. Revisit if deep operator nesting
turns out to matter in practice - e.g. by moving the operator-alternation
check to a SPARQL-based constraint the same way the list shape was.
"""

from __future__ import annotations

import warnings
from pathlib import Path

from rdflib import Graph

from ..expr_families import _EXPR_NODE_FAMILY
from . import ontology_graph

try:
    from pyshacl import validate as _pyshacl_validate
    from pyshacl.errors import ShapeRecursionWarning
except ImportError as exc:  # pragma: no cover - exercised only when pyshacl isn't installed
    raise ImportError(
        "starsparql.shapes requires pyshacl - install with "
        "`pip install -e '.[test]'` or `pip install pyshacl`"
    ) from exc

SPARQL_SHAPES_TTL_PATH = Path(__file__).parent / "sparql_shapes.ttl"

# The hand-authored shapes below used to be a giant inline Python string
# (SHAPES_TURTLE = """...""", ~1700 lines) - moved to a standalone
# sparql_shapes.ttl file 2026-08-16, mirroring salg-ontology.ttl's own
# already-established pattern (a real, directly-usable Turtle file, not a
# Python string), so it's directly usable by any RDF tool without going
# through this module. Every embedded sh:select query body's own
# """...""" delimiters no longer need Python-level backslash-escaping
# now that they are not nested inside a Python triple-quoted string.
SHAPES_TURTLE = SPARQL_SHAPES_TTL_PATH.read_text()


def _generate_expression_shapes_turtle() -> str:
    """The 63 short per-expression-node-name declarations, each pointing
    at its family's reusable body shape via ``sh:node`` - generated from
    ``_EXPR_NODE_FAMILY`` rather than hand-written. See that table's own
    docstring for why.
    """
    declarations = [
        f"salg:{name}Shape a sh:NodeShape ; sh:targetClass salg:{name} ; "
        f"sh:node salg:_{family}ExprBodyShape ."
        for name, family in _EXPR_NODE_FAMILY.items()
    ]
    return "\n".join(declarations) + "\n"


def shapes_graph() -> Graph:
    """A fresh ``rdflib.Graph`` of the shapes above (SHACL graphs are
    mutated by pyshacl during validation, so callers get their own copy
    rather than a shared module-level instance)."""
    turtle = SHAPES_TURTLE + "\n" + _generate_expression_shapes_turtle()
    g = Graph()
    g.parse(data=turtle, format="turtle")
    return g


def validate(data_graph: Graph) -> tuple[bool, Graph, str]:
    """Validate ``data_graph`` (e.g. from ``to_rdf.query_to_rdf``, or an
    LLM-authored ``salg:`` graph not yet decoded) against the shapes above.

    Runs with RDFS reasoning enabled (``ont_graph=ontology_graph()``,
    ``inference="rdfs"``) - this is what lets ``GraphPatternShape``/
    ``ExpressionShape``/``SubSelectShape`` be a single ``sh:class`` check
    against an abstract superclass (``salg:GraphPattern``/``salg:Expression``/
    ``salg:SubSelect``) instead of enumerating every concrete
    operator/builtin by name: with reasoning on, a node asserted as e.g.
    ``salg:Builtin_STR`` is *also* entailed to be ``rdf:type``
    ``salg:OneArgExpression`` and ``salg:Expression`` (the ontology's own
    ``rdfs:subClassOf`` chain), so ``sh:class salg:Expression`` alone
    matches it - confirmed empirically, not assumed. Every individual
    operator/builtin shape (``BGPShape``, ``Builtin_STRShape``, ...) is
    unaffected either way - RDFS subclass reasoning only ever *adds*
    broader inferred types to an already-narrowly-typed node, never
    invents narrower ones, so ``sh:targetClass salg:Builtin_STR`` still
    fires only for nodes actually asserted as that type.

    Returns ``(conforms, results_graph, results_text)`` — the same shape
    ``pyshacl.validate`` itself returns, so a caller that wants the raw
    SHACL validation report can use it directly.
    """
    # No shape in this file's dispatch shapes (GraphPatternShape/
    # ExpressionShape/SubSelectShape) references another shape by name
    # anymore (sh:class, not sh:node/sh:or-of-shapes - see each one's own
    # comment in SHAPES_TURTLE), so pyshacl's shape-recursion guard
    # shouldn't have anything left to trip on. Kept as a defensive
    # suppression, not because it's expected to fire.
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=ShapeRecursionWarning)
        conforms, results_graph, results_text = _pyshacl_validate(
            data_graph,
            shacl_graph=shapes_graph(),
            ont_graph=ontology_graph(),
            inference="rdfs",
            advanced=True,
            max_validation_depth=100,
        )
    return conforms, results_graph, results_text
